services:
  app01:
    image: hibernate-demo/hsearch-outbox-polling:1.0.0-SNAPSHOT
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://pg01:5432/hibernate_demo
      - QUARKUS_DATASOURCE_USERNAME=hibernate_demo
      - QUARKUS_DATASOURCE_PASSWORD=hibernate_demo
      - QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS=es01:9200,es02:9200
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
      - QUARKUS_HIBERNATE_SEARCH_ORM_SCHEMA_MANAGEMENT_STRATEGY=drop-and-create-and-drop
    ports:
      - 8080:8080
      - 9000:9000
    networks:
      - appnet
      - pgnet
      - esnet
    depends_on:
      pg01:
        condition: service_healthy
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
    healthcheck:
      test: curl -f -s http://app01:9000/q/health >/dev/null || exit 1
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 2s
  app02:
    image: hibernate-demo/hsearch-outbox-polling:1.0.0-SNAPSHOT
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://pg01:5432/hibernate_demo
      - QUARKUS_DATASOURCE_USERNAME=hibernate_demo
      - QUARKUS_DATASOURCE_PASSWORD=hibernate_demo
      - QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS=es01:9200,es02:9200
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=none
    networks:
      - pgnet
      - esnet
    depends_on:
      pg01:
        condition: service_healthy
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      app01:
        condition: service_healthy
    healthcheck:
      test: curl -f -s http://app02:9000/q/health >/dev/null || exit 1
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 2s
  pg01:
    image: postgres:14
    environment:
      - POSTGRES_USER=hibernate_demo
      - POSTGRES_PASSWORD=hibernate_demo
      - POSTGRES_DB=hibernate_demo
      # For healthchecks
      - PGUSER=hibernate_demo
      - PGPASSWORD=hibernate_demo
      - PGDATABASE=hibernate_demo
    ports:
      - 5432:5432
    networks:
      - pgnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 15s
  es01:
    image: elastic/elasticsearch:8.9.1
    environment:
      - node.name=es01
      - xpack.security.enabled=false
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    networks:
      - esnet
    healthcheck:
      test: curl -s http://es01:9200 >/dev/null || exit 1
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 15s
  es02:
    image: elastic/elasticsearch:8.9.1
    environment:
      - node.name=es02
      - xpack.security.enabled=false
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cap_add:
      - IPC_LOCK
    networks:
      - esnet
    healthcheck:
      test: curl -s http://es02:9200 >/dev/null || exit 1
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 15s

networks:
  esnet:
  pgnet:
  appnet:
