version: '3.1'
services:
  pg01:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=hibernate_demo
      - POSTGRES_PASSWORD=hibernate_demo
      - POSTGRES_DB=hsearch_es_wikipedia
    volumes:
      - pgdata01:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pgnet
  es01:
    image: elastic/elasticsearch:8.9.0
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # Self-signed certificates really aren't practical to work with, so we disable that.
      - xpack.security.enabled=false
      # Disable disk-based shard allocation thresholds: on large, relatively full disks (>90% used),
      # it will lead to index creation to get stuck waiting for other nodes to join the cluster,
      # which will never happen since we only have one node.
      # See https://www.elastic.co/guide/en/elasticsearch/reference/8.9/modules-cluster.html#disk-based-shard-allocation
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: elastic/elasticsearch:8.9.0
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # Self-signed certificates really aren't practical to work with, so we disable that.
      - xpack.security.enabled=false
      # Disable disk-based shard allocation thresholds: on large, relatively full disks (>90% used),
      # it will lead to index creation to get stuck waiting for other nodes to join the cluster,
      # which will never happen since we only have one node.
      # See https://www.elastic.co/guide/en/elasticsearch/reference/8.9/modules-cluster.html#disk-based-shard-allocation
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  pgdata01:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
  pgnet:
