# Spring Boot configuration
# See https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# for a list of available properties

app:
  data.path: /home/${user}/tmp/hsearch-elasticsearch-wikipedia

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://localhost:5432/hsearch_es_wikipedia
  username: hibernate_demo
  password: hibernate_demo
  hikari:
    maximumPoolSize: 30

spring.jpa.properties:
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
  hibernate.search:
    lucene_version: LUCENE_5_5_4
    default:
      directory_provider: filesystem
      indexBase: ${app.data.path}/lucene/

spring.jackson:
  serialization:
    INDENT_OUTPUT: true
  default-property-inclusion: NON_NULL

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.search.batchindexing: INFO
  org.hibernate.search.fulltext_query: DEBUG