spring.jpa:
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate.search:
      schema_management.strategy: drop-and-create-and-drop
      backend:
        automatic_indexing:
          synchronization.strategy: sync

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.search.massindexing: INFO
  org.hibernate.search.query: TRACE
  org.hibernate.search.elasticsearch.request: TRACE
