# Spring Boot configuration
# See https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# for a list of available properties

app:
  data.path: /home/${user}/tmp/hsearch-elasticsearch-wikipedia

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://localhost:5432/hsearch_es_wikipedia
  username: hibernate_demo
  password: hibernate_demo
  hikari:
    maximumPoolSize: 30

spring.jpa.properties:
  hibernate.search:
    schema_management.strategy: create-or-validate
    backend:
      hosts: localhost:9200
      protocol: http
      discovery.enabled: true
      analysis.configurer: analysisConfigurerSpringBean
      # This fixes mass indexing by reducing the amount of parallel indexing requests:
      # our cluster is not large enough to handle high parallel traffic.
      # Of course this also means mass indexing gets quite slow,
      # so one might want to bump the numbers to get more throughput
      # (but risk failures if the cluster gets overloaded).
      indexing.queue_count: 2
      indexing.max_bulk_size: 100

spring.jackson:
  serialization:
    INDENT_OUTPUT: true
  default-property-inclusion: NON_NULL

logging.level:
  # Uncomment for extensive SQL logging
  #org.hibernate.SQL: DEBUG
  org.hibernate.search.massindexing: INFO
  org.hibernate.search.query: TRACE
  #org.hibernate.search.elasticsearch.request: DEBUG
  #org.hibernate.search.engine.backend.orchestration.spi: DEBUG
